In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


Reshaping arrays via pre-defined list (c) or user defined np.array([0,1,...XYZ])

In [6]:
c = np.array([[0, 1, 2], [3, 4, 5]])

In [7]:
d = c.reshape(2,3)
print(d)

[[0 1 2]
 [3 4 5]]


In [8]:
np.array([0,1,2,3,4,5]).reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

9 number array into 3x3 matrix

In [26]:
matrix = np.array([0,1,np.nan,3,4,np.nan,6,7,8]).reshape(3, 3)
print(matrix)

[[ 0.  1. nan]
 [ 3.  4. nan]
 [ 6.  7.  8.]]


In [28]:
np.isnan(matrix)

array([[False, False,  True],
       [False, False,  True],
       [False, False, False]])